// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"ucenter-api/internal/svc"
)

func RegisterHandlers(r *Routers, serverCtx *svc.ServiceContext) {

	// 如果要是有中间件怎么办
	register := NewRegisterHandler(serverCtx)
	registerRouter := r.Group()
	registerRouter.Post("/uc/register/phone", register.Register)
	registerRouter.Post("/uc/mobile/code", register.SendCode)

	loginRouter := r.Group()
	login := NewLoginHandler(serverCtx)

	loginRouter.Post("/uc/login", login.Login)
	loginRouter.Post("/uc/check/login", login.CheckLogin)
}
