// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

// Code generated by goctl. DO NOT EDIT.

type RateRequest struct {
	Unit string `path:"unit" json:"unit"`
	Ip   string `json:"ip,optional"`
}
type RateResponse struct {
	Rate float64 `json:"rate"`
}
