// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"market-api/internal/svc"
)

func RegisterHandlers(r *Routers, serverCtx *svc.ServiceContext) {

	// 如果要是有中间件怎么办
	rate := NewExchangeRateHandler(serverCtx)
	exchangeRouter := r.Group()
	exchangeRouter.Post("/exchange-rate/usd/:unit", rate.UsdRate)

	market := NewMarketHandler(serverCtx)
	marketRouter := r.Group()
	marketRouter.Post("/symbol-thumb-trend", market.SymbolThumbTrend)
}
