// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: ucclient.proto

package mclient

import (
	"context"
	"grpc-common/market/types/rate"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	RateReq = rate.RateReq
	RateRes = rate.RateRes

	ExchangeRate interface {
		UsdRate(ctx context.Context, in *RateReq, opts ...grpc.CallOption) (*RateRes, error)
	}

	defaultRate struct {
		cli zrpc.Client
	}
)

func NewRate(cli zrpc.Client) ExchangeRate {
	return &defaultRate{
		cli: cli,
	}
}

func (m *defaultRate) UsdRate(ctx context.Context, in *RateReq, opts ...grpc.CallOption) (*RateRes, error) {
	client := rate.NewExchangeRateClient(m.cli.Conn())
	return client.UsdRate(ctx, in, opts...)
}
